apiVersion: v1
kind: Service

metadata:
  name: {{ template "phpldapadmin.fullname" . }}
  labels:
    app: {{ template "phpldapadmin.name" . }}
    chart: {{ template "phpldapadmin.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port | default 80 }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ template "phpldapadmin.name" . }}
    release: {{ .Release.Name }}
